name: initial run

on: [push]

jobs:
  Environment:
    runs-on: ubuntu-latest
    steps:
      - name: Environment
        run: sudo apt update
        run: sudo apt install python3-venv
        run: python3 -m venv myenv
        run: source myenv/bin/activate
        run: pip3 install s3fs pandas scikit-learn
