name: initial run

on: [push]

jobs:
  Environment:
    runs-on: ubuntu-latest
    steps:
      - name: dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-venv
      - name: venv
        run: |
          python3 -m venv myenv
          source myenv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install s3fs pandas scikit-learn
